from alembic import op
import sqlalchemy as sa


revision = 'd5121a7dd77a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This backend's tables live in their own "app" schema, kept separate
    # from the annotation team's "bronze" schema in the same shared
    # Supabase project. Postgres doesn't create schemas on the fly.
    op.execute('CREATE SCHEMA IF NOT EXISTS app')

    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('dataset', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_username'), 'users', ['username'], unique=True, schema='app')
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('annotation_status', sa.String(length=32), nullable=False),
    sa.Column('annotation_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['app.cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos', schema='app')
    op.drop_table('saved_queries', schema='app')
    op.drop_index(op.f('ix_app_users_username'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    op.drop_table('cameras', schema='app')
    # Deliberately not dropping the "app" schema itself here — safer if
    # anything else ever gets added to it outside of Alembic.
    # ### end Alembic commands ###
